# Generated by Django 3.2.23 on 2023-12-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
