# Generated by Django 3.2.23 on 2024-01-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
